name: add-files-to-release

on:
  workflow_run:
    workflows: ["goreleaser"]
    types:
      - completed

jobs:
  add-files-to-release:
    name: Build and upload docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Put testnet artifacts into a single zip
        run: |
          mkdir -p testnet/config/environments/public
          cp config/environments/public/* testnet/config/environments/public
          cp docker-compose.yml testnet
          mv testnet/config/environments/public/example.env testnet
          sed -i -e 's/image: zkevm-node/image: zkevm-node:${{ github.ref }}/g' testnet/docker-compose.yml
          zip -r testnet.zip testnet
      - name: Upload to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'testnet.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref }}